apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataset-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dataset-operator
  template:
    metadata:
      labels:
        name: dataset-operator
    spec:
      serviceAccountName: dataset-operator
      containers:
        - name: dataset-operator
          # Replace this with the built image name
          image: ${DATASET_OPERATOR_IMAGE}
          command:
          - dataset-operator
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: webhook-api
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "dataset-operator"
          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /run/secrets/tls
              readOnly: true
      imagePullSecrets:
        - name: ${DOCKER_REGISTRY_SECRET}
      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: webhook-server-tls
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
spec:
  selector:
    name: dataset-operator
  ports:
    - port: 443
      targetPort: webhook-api